name = "AASparseSolvers"
uuid = "d100da09-6e2e-46b6-9bcf-677f5299069c"
authors = ["Kiernan, Luke <Luke.Kiernan@nrel.gov>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
LinearAlgebra = "1.11.0"
SparseArrays = "1.11.0"
Test = "1.11.0"
